# Site settings
title: Avenue 32
description: >
  Secret Escapes have partnered with Avenue 32 to bring you a competition destined for catwalk flaunts and stylish jaunts.
baseurl: "/avenue32" # the subpath of your site, e.g. /blog/
url: "http://mp.secretescapes.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, bower_components, bower.json, README.md]
